
parameter_defaults:
  InternalApiNetCidr: 192.168.120.0/24
  StorageNetCidr: 192.168.130.0/24
  StorageMgmtNetCidr: 192.168.140.0/24
  TenantNetCidr: 192.168.150.0/24
  ExternalNetCidr: 10.255.5.192/27
  ControlPlaneSubnetCidr: '24'
  InternalApiAllocationPools: [{'start': '192.168.120.10', 'end': '192.168.120.120'}]
  StorageAllocationPools: [{'start': '192.168.130.10', 'end': '192.168.130.120'}]
  StorageMgmtAllocationPools: [{'start': '192.168.140.10', 'end': '192.168.140.120'}]
  TenantAllocationPools: [{'start': '192.168.150.10', 'end': '192.168.150.120'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '10.255.5.201', 'end': '10.255.5.202'}]
  ExternalInterfaceDefaultRoute: 10.255.5.193
  ControlPlaneDefaultRoute: 192.168.66.18
  EC2MetadataIp: 192.168.66.18
  DnsServers: ["10.255.0.1"]
  NtpServer:  ["192.168.66.18"]
  InternalApiNetworkVlanID: 120
  StorageNetworkVlanID: 130
  StorageMgmtNetworkVlanID: 140
  TenantNetworkVlanID: 150
  ExternalNetworkVlanID: 576
  NeutronExternalNetworkBridge: "''"
  BondInterfaceOvsOptions: "mode=active-backup"

  NetworkDeploymentActions: ['CREATE','UPDATE']
#  BaremetalNetCidr: 10.12.134.0/24
#  BaremetalAllocationPools: [{'start': '10.12.134.25', 'end': '10.12.134.30'}]
#  BaremetalNetworkVlanID: 1134

 ######  
 # SRIOV
 ######
#  NeutronTunnelTypes: ''
  NeutronTunnelTypes: ""
  NeutronNetworkType: 'vlan'
  NeutronNetworkVLANRanges: "datacentre:201:300,sriov1:204:204"
    
  NeutronPhysicalDevMappings: "sriov1:ens1f1"
  NeutronBridgeMappings: 'datacentre:br-all,sriov1:br-link0'
#  NeutronSupportedPCIVendorDevs: ['8086:154c']
 
  ComputeSriovParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=32 iommu=pt intel_iommu=on"
    #TunedProfileName: "cpu-partitioning"
    #IsolCpusList: "1,2,3,4,5,6,7,9,10,17,18,19,20,21,22,23,11,12,13,14,15,25,26,27,28,29,30,31"
    IsolCpusList: "0,44"
    #NovaVcpuPinSet: ['1,2,3,4,5,6,7,9,10,17,18,19,20,21,22,23,11,12,13,14,15,25,26,27,28,29,30,31']
    NovaReservedHostMemory: 4096
    NeutronSriovNumVFs:
      - "ens1f1:16"
    NovaPCIPassthrough:
      - devname: "ens1f1"
        physical_network: "sriov1"
    
  # DHCP provide metadata route to VM.
    NeutronEnableIsolatedMetadata: true
  # DHCP always provides metadata route to VM.
    NeutronEnableForceMetadata: true


  controllerExtraConfig:
    neutron::agents::dhcp::enable_isolated_metadata: true

#  rhel_reg_activation_key: "osp13-dev"
#  rhel_reg_auto_attach: ""
#  rhel_reg_base_url: ""
#  rhel_reg_environment: ""
#  rhel_reg_force: "true"
#  rhel_reg_machine_name: ""
#  rhel_reg_org: "brentandkrysti"
#  rhel_reg_password: ""
#  rhel_reg_pool_id: ""
#  rhel_reg_release: ""
#  rhel_reg_repos: ""
#  rhel_reg_sat_url: "http://satellite6.home.brentandkrysti.com"
#  rhel_reg_server_url: ""
#  rhel_reg_service_level: ""
#  rhel_reg_user: ""
#  rhel_reg_type: ""
#  rhel_reg_method: "satellite"
#  rhel_reg_sat_repo: "rhel-7-server-satellite-tools-6.2-rpms"
#  rhel_reg_http_proxy_host: ""
#  rhel_reg_http_proxy_port: ""
#  rhel_reg_http_proxy_username: ""
#  rhel_reg_http_proxy_password: ""

  OvercloudControlFlavor: control
  OvercloudComputeSriovFlavor: compute
  ControllerCount: 1
  ComputeSriovCount: 4


  NovaSchedulerDefaultFilters:
    - RetryFilter
    - AvailabilityZoneFilter
    - AggregateRamFilter
    - AggregateCoreFilter
    - ComputeFilter
    - AggregateInstanceExtraSpecsFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - RamFilter
    - DiskFilter
    - PciPassthroughFilter


  NovaSchedulerAvailableFilters:
    - nova.scheduler.filters.all_filters
    - nova.scheduler.filters.pci_passthrough_filter.PciPassthroughFilter

#  IronicCleaningDiskErase: metadata
#  IronicCleaningNetwork:

#  ServiceNetMap:
#    IronicApiNetwork: external
#    IronicNetwork: external

  SSLRootCertificate: |
    -----BEGIN CERTIFICATE-----
    MIIDjTCCAnWgAwIBAgIQQ+k4pX94S1e79ah9tYcpXTANBgkqhkiG9w0BAQsFADBQ
    MSAwHgYDVQQDDBdMb2NhbCBTaWduaW5nIEF1dGhvcml0eTEsMCoGA1UEAwwjNDNl
    OTM4YTUtN2Y3ODRiNTctYmJmNWE4N2QtYjU4NzI5NWQwHhcNMTgwODA5MDk0NzM1
    WhcNMTkwODA5MDk0NzM1WjBQMSAwHgYDVQQDDBdMb2NhbCBTaWduaW5nIEF1dGhv
    cml0eTEsMCoGA1UEAwwjNDNlOTM4YTUtN2Y3ODRiNTctYmJmNWE4N2QtYjU4NzI5
    NWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDi+Xhd0NBL9ghBiuwP
    ofI7JytwzETWXq6mOvvIJL1G3BJIVxhExIrLuFm4WJfcT0/fQGgn5Ty1vV9Hi5iE
    uenI+8kgpcBicyHc+YrAL4pZ1BwqZDkTQcj8TcNbjdxs8y6M2+xwiw/omxR8Y2R4
    RvPeOfw16I/Ck1rVkyJGmt0niAZOwOxPU0Dx+jDFTSc93wbj2i+TyUHZudOwz/DD
    pnEJogwngZI2fTPACygUOUDq4nLkCTmPbSTYVmd8DhQ8nOIwJ9Ymd8rjwOUUbQBG
    KRBIWhktA5PyLb7FsXw67V8m+Irb+lhgs3boRxN4RBScSdEmAlKkVv1sm+tHuF84
    WqmhAgMBAAGjYzBhMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFGRyQBQ/E/9I
    2Qa+GaC4U7FmBhz5MB8GA1UdIwQYMBaAFGRyQBQ/E/9I2Qa+GaC4U7FmBhz5MA4G
    A1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAQEAQIoB9OemoOiwegE/TLpG
    k0QqOImiEFQTtrp5gJn1cLlWBnakJAd5oJxg0mryOmnjKSeHZRCWd+xHLKz5I+Fq
    h7rt4UAXC3Zc0DB3TXVaEU9aF2j7kmYYAUG86Rd2OSV6ozYOToc7DH30+VC+PNiB
    9v33DgexA8yofQNr/d+IIH6siy9jvmsVzYQHmEzxWO5prtrAnv+T/GVBSIERxbOu
    rcqalYXChvhg7C8DxAZqvwJYYAq2KH6vC/i+IJ24pXKN0FYVrO1IRY2wWcRahloL
    0cmcLy1jaYvJyjk1K5gOOgTBYrpHarK2/mRs4VVGdP7HFhDzX/HxCXM50929k3Jp
    lA==
    -----END CERTIFICATE-----


  PublicVirtualFixedIPs: [{'ip_address':'10.255.5.201'}]
  ControllerIPs:
    external:
    - 10.255.5.207
    - 10.255.5.208
    - 10.255.5.209
